#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates the auto-generated evidence block in docs/trickster-study.md
# from the live Atlas indexes, so the study never carries stale hardcoded
# figures. Mirrors the logic of site-next/src/pages/trickster/index.astro,
# which reads the same indexes at site build time.
#
# Usage: ruby scripts/build_trickster_study_figures.rb

require "yaml"

ROOT = File.expand_path("..", __dir__)
DOC = File.join(ROOT, "docs", "trickster-study.md")
BEGIN_MARK = "<!-- TRICKSTER-FIGURES:BEGIN — auto-generated by scripts/build_trickster_study_figures.rb; do not edit by hand -->"
END_MARK = "<!-- TRICKSTER-FIGURES:END -->"

freq = YAML.load_file(File.join(ROOT, "data", "indexes", "canonical-motif-frequency.yml"))
cons = YAML.load_file(File.join(ROOT, "data", "indexes", "motif-constellations.yml"))
crown = YAML.load_file(File.join(ROOT, "data", "indexes", "crown-independent-taxonomy.yml"))

fam = freq.fetch("canonical_motifs").find { |f| f["canonical_motif_id"] == "trickster" }
abort "trickster family not found in canonical-motif-frequency.yml" unless fam

dominant = fam.fetch("mapped_motifs").max_by { |m| m["occurrence_count"] || 0 }

# Vivid child-motif labels, kept only while they still exist in the family.
VIVID = [
  "trickster deceives a dangerous being through staged self-harm",
  "Animal or bird relay of stolen fire",
  "Cannibal tree-dweller destroyed by concealed fire",
  "Sticky tar baby or molded gum-ball story variant",
  "Swallowed animal kills the swallower from inside",
  "comic animal bargain through flattery",
  "ambiguous truth used as fatal deception",
  "absurd staged evidence discredits a true report",
  "Feigned death as a lure",
  "clever thief completes imposed task and wins wager",
].freeze
labels = fam["mapped_motifs"].map { |m| (m["label"] || "").downcase }
vivid = VIVID.select { |v| labels.include?(v.downcase) }

bonds = cons.fetch("conserved_edges")
  .select { |e| (e["pair"] || []).include?("trickster") }
  .map do |e|
    { partner: (e["pair"] - ["trickster"]).first,
      traditions: e["tradition_count"],
      cooccurrences: e["total_cooccurrences"] }
  end
  .sort_by { |b| [-b[:traditions], -b[:cooccurrences]] }
strongest = bonds.first

primary_k = crown.fetch("primary_k")
result = crown.fetch("results").find { |r| r["k"] == primary_k }
matched = result.fetch("matched_bonds") || []
bond_text = lambda do |b|
  [b["iso_cluster_a"], b["iso_cluster_b"], b["con_cluster_a"], b["con_cluster_b"]]
    .flatten.compact.join(" ")
end
trick_re = /trickster|coyote|raven/i
trick_bonds = matched.select { |b| trick_re.match?(bond_text.call(b)) }

THEMES = [
  ["ritual / offering", /ritual|offering|sacrifice|purificat|libation|prayer|feast/i],
  ["afterlife / death / return", /afterlife|death|dead|underworld|resurrect|revive|return|funeral|grave|soul|ghost/i],
  ["battle / war", /battle|\bwar\b|combat|warrior|fight|slay|duel|raid/i],
  ["marriage / union", /marriage|marry|\bwed|bride|groom|union|courtship|abduct/i],
  ["emergence / creation", /creation|emergence|origin|primordial|cosmos|world[- ]|first (man|people)/i],
  ["healing", /heal|cure|medicine|restore|revive/i],
  ["trickster / theft by cunning", /trickster|coyote|raven|decept|deceiv|trick|steal|theft|disguise/i],
].freeze
tally = THEMES.map { |(t, re)| [t, matched.count { |b| re.match?(bond_text.call(b)) }] }
  .sort_by { |(_, n)| -n }

fmt = ->(n) { n.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\1,').reverse }

lines = []
lines << BEGIN_MARK
lines << ""
lines << "*(figures regenerated #{Time.now.utc.strftime('%Y-%m-%d')} from the " \
         "three indexes cited below — run " \
         "`ruby scripts/build_trickster_study_figures.rb` to refresh)*"
lines << ""
lines << "**The `trickster` family** (`data/indexes/canonical-motif-frequency.yml`,"
lines << "`canonical_motif_id: trickster`, label *\"#{fam['label']}\"*):"
lines << ""
lines << "- **#{fam['tradition_count']} traditions** hold him."
lines << "- **#{fmt.call(fam['occurrence_count'])}** tagged occurrences."
lines << "- The family's own definition: *\"#{fam['description'].strip.gsub(/\s+/, ' ')}\"*"
lines << "- Its declared kin (`related`): #{(fam['related'] || []).map { |r| "`#{r}`" }.join(', ')}."
lines << "- **#{fam['mapped_motif_count']}** distinct child-motifs are mapped into the family."
lines << ""
lines << "**The dominant child-motif is liminality, empirically.** Of the " \
         "#{fam['mapped_motif_count']} children, one towers over the rest:"
lines << ""
lines << "- **\"#{dominant['label']}\" — #{fmt.call(dominant['occurrence_count'])} occurrences " \
         "across #{dominant['tradition_count']} traditions.**"
lines << ""
lines << "The next-largest children are a very long tail of sparse, richly-specific"
lines << "labels. Whatever else the trickster does, the corpus says his most-repeated"
lines << "single act is to *stand where two orders meet*. The vivid tail includes real"
lines << "labels such as:"
lines << ""
vivid.each { |v| lines << "- *#{v}*" }
lines << ""
lines << "**His position in the web** (`data/indexes/motif-constellations.yml`,"
lines << "`conserved_edges` — family-pairs that co-occur so reliably across so many"
lines << "unrelated traditions that chance cannot explain the partnership). The trickster"
lines << "holds **#{bonds.length} conserved bonds**. In descending strength:"
lines << ""
lines << "| Partner family | Traditions | Co-occurrences |"
lines << "|---|---|---|"
bonds.each_with_index do |b, i|
  cells = [b[:partner], b[:traditions], fmt.call(b[:cooccurrences])].map(&:to_s)
  cells = cells.map { |c| "**#{c}**" } if i.zero?
  lines << "| #{cells.join(' | ')} |"
end
lines << ""
lines << "His single strongest tie, in **#{strongest[:traditions]} traditions** " \
         "(#{fmt.call(strongest[:cooccurrences])} co-occurrences), is with " \
         "**#{strongest[:partner].tr('_', ' ')}**: the thief of fire, forever caught mid-theft."
lines << ""
lines << "**The crown finding** (`data/indexes/crown-independent-taxonomy.yml`,"
lines << "primary k = #{primary_k}, verdict #{crown['verdict']}). Of the " \
         "**#{matched.length} matched cross-world bonds**, counting how often each theme"
lines << "carries in either independently-built world:"
lines << ""
lines << "| Theme | Appears in (of #{matched.length}) |"
lines << "|---|---|"
tally.each do |(theme, n)|
  row = theme.include?("trickster") ? "| **#{theme}** | **#{n}** |" : "| #{theme} | #{n} |"
  lines << row
end
lines << ""
lines << "The trickster's matched bonds number **#{trick_bonds.length} of #{matched.length}**."
trick_bonds.each do |b|
  on_a = trick_re.match?((b["iso_cluster_a"] || []).join(" "))
  own = on_a ? b["iso_cluster_a"] : b["iso_cluster_b"]
  lines << "- iso cluster *\"#{(own || []).first(3).join(' / ')}\"* — " \
           "`iso_weight #{b['iso_weight']}`, `con_weight #{b['con_weight']}`."
end
lines << ""
lines << END_MARK

block = lines.join("\n")

doc = File.read(DOC)
pattern = /#{Regexp.escape(BEGIN_MARK)}.*?#{Regexp.escape(END_MARK)}/m
abort "markers not found in #{DOC}" unless doc.match?(pattern)
File.write(DOC, doc.sub(pattern, block))
puts "Updated #{DOC}: #{fam['tradition_count']} traditions, " \
     "#{fam['occurrence_count']} occurrences, #{bonds.length} bonds, " \
     "#{trick_bonds.length}/#{matched.length} crown bonds."
